name: kinematic_chain_path_finding
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  json_annotation: ^4.9.0
  mobx: ^2.4.0
  mobx_codegen: ^2.6.2
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  leancode_lint: ^14.2.0

flutter:
  uses-material-design: true
